spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Grupo-12-BDD-OO2-2020?autoReconnect=true&useSSL=false
    username: root
    password: 
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      dialect: org.hibernate.dialect.MySQL5Dialect
  thymeleaf:
    cache: false
